version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: mydb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senhadomysql
    ports:
      - 3306:3306
  airflow:
    image: airflow:latest
    container_name: airflow
    depends_on:
      - db
    command: >
      bash -c "cd /root/airflow; airflow scheduler"
    volumes:
      - /root/airflow/airflow.cfg:/root/airflow/airflow.cfg
      - /root/airflow/webserver_config.py:/root/airflow/webserver_config.py
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
      - /root/airflow/dags:/root/airflow/dags
      - /docker/data/:/docker/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080


